# Reference: https://github.com/redhat-cop/redhat-image-mode-actions
name: Build RHEL bootc image with GHA
on:
  workflow_dispatch:
  push:

jobs:
  build-tegra-llm-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Pull container image
        run: |
          podman pull quay.io/fedora/fedora-bootc:42
      - name: Build raw image
        id: build-raw-img
        uses: osbuild/bootc-image-builder-action@v0.0.2
        with:
          config-file: ./config.toml
          image: quay.io/fedora/fedora-bootc:42
          rootfs: xfs
          types: |
            raw
